### ISSUE TITLE
HB_SolveAdjacency command message error

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-rhino-plugin#111]
![image](https://user-images.githubusercontent.com/2915573/78502820-ff162b80-7730-11ea-991d-2b0bda65ca74.png)

The message is for the MassToRoom command.

**Comment by mostaphaRoudsari** [comment]
HB_GetInfo has the same issue.

![image](https://user-images.githubusercontent.com/2915573/78503012-0be74f00-7732-11ea-85f8-3ddf50cefe0e.png)

**Comment by MingboPeng** [comment]
addressed: https://github.com/ladybug-tools/honeybee-rhino-plugin/commit/3772ea186ae0ab9aae4a7f3ac6e0c83db779f572
