### ISSUE TITLE
Document honeybee commands

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-rhino-plugin#113]
I don't know if there is an easy way to do this but is it possible to generate the documentation for Honeybee commands that we are adding to Rhino?

Something simple as markdown file should be enough to list the name of command and a short description. We can also write a script to do that if there is an XML file or some other document that can parse it.

**Comment by MingboPeng** [comment]
I am able to generate a xml file for all types, parameters' summary (annotation) for every build.
![image](https://user-images.githubusercontent.com/9031066/78615849-9027f800-7840-11ea-9b69-338667166651.png)

Do you know any easy way to convert this to a markdown file?
@mostaphaRoudsari

**Comment by mostaphaRoudsari** [comment]
We can write a Python script to do that. Can you share a sample file with me?

**Comment by mostaphaRoudsari** [comment]
Also can you generate the options with their default values if any? Basically as much as details as possible.

**Comment by MingboPeng** [comment]
Try this one:
Please only look at these two:
"**T:HoneybeeRhino.RhinoCommands**.HB_AddWindowByWWR"
"**T:HoneybeeRhino.RhinoCommands**.HB_MassToRoom"


[HoneybeeRhinoPlugIn.zip](https://github.com/ladybug-tools/honeybee-rhino-plugin/files/4441395/HoneybeeRhinoPlugIn.zip)

**Comment by mostaphaRoudsari** [comment]
I did a quick test and the parsing is easy. We can generate something like the text below. A couple of questions for you:

1. What's the difference between the commands that starts with `P:` and the ones that starts with `T:`? Do we want to have both?
2. Should I only include the commands that starts with `HB_` or we should include commands like BrepJson?
3. Did you manually write the descriptions with `options:` part or is it auto-generated? If it is manual then I have some suggestions to format them better. If it is automated then I can improve the parser to make them look better.

Let me know what you think?

# Honeybee Rhino Commands

## `BrepJson`

The only instance of the GetBrepJson command.

## `HB_AddShades`

The only instance of the MyCommand1 command.

## `HB_AddWindowByWWR`

Use this command to add windows by window to wall ratio for each outdoor walls of selected honeybee rooms.
**Options:**
* **WindowWallRatio**: set a number between 0 to 1 for WWR.(default:0.6)
* **SkipFacesWithWindows**: set to Yes to only generate windows on walls that do not have existing windows. (default:Yes)

## `HB_AddWindowByWWR`

The only instance of the HB_AddWindowByWWR command.

## `HB_AddDoors`

The only instance of the MyCommand1 command.

## `HB_AddWindowToRoom`

The only instance of the MyCommand1 command.

## `HB_Constructions`

The only instance of the HB_Constructions command.

## `HB_Model`

The only instance of the HB_CreateHBModel command.

## `HB_EditRoom`

The only instance of the HB_GetInfo command.

## `HB_GetInfo`

This is only available for development.

## `HB_GetInfo`

The only instance of the HB_GetInfo command.

## `HB_MassToRoom`

Use this command to convert closed geometries to honeybee rooms. 
            Options:
            -SkipExistingRoom: set to Yes to only convert non-honeybee-room geometries

## `HB_MassToRoom`

The only instance of the MyCommand1 command.

## `HB_RunSimu`

The only instance of the HB_RunSimu command.

## `HB_SetRoomEnergyProperties`

The only instance of the HB_ProgramTypes command.

## `HB_SimulationParameter`

The only instance of the HB_SimulationParameters command.

## `HB_SolveAdjacency`

The only instance of the HB_SolveAdjancy command.

**Comment by mostaphaRoudsari** [comment]
Here is the code. You need to install `xmltodict` library.

`pip install xmltodict`

```python
import xmltodict

fp = r"HoneybeeRhinoPlugIn.xml"

with open(fp, 'r') as inf:
    data = xmltodict.parse(inf.read())

commands = [
    member for member in data['doc']['members']['member']
    if ':HoneybeeRhino.RhinoCommands.' in member['@name']
]

with open('test.md', 'w') as out_file:
    for member in commands:
        name = member['@name'].split('.RhinoCommands.')[-1].replace('.Instance', '')
        description = member['summary']
        out_file.write('## `%s`\n\n' % name)
        out_file.write(description + '\n\n')

```

**Comment by MingboPeng** [comment]
Thanks @mostaphaRoudsari ,

- **What's the difference between the commands that starts with P: and the ones that starts with T:? Do we want to have both?**
"P" means it is a property, "T": Type. We just need to deal with types. And I found it xml doesn't include any types if they don't have summary annotation. 

- **Should I only include the commands that starts with HB_ or we should include commands like BrepJson?**

BrepJson is one command I want to use for serialize Brep for testing purpose, so we only include the commands starts with HB_.

- **Did you manually write the descriptions with options: part or is it auto-generated? If it is manual then I have some suggestions to format them better. If it is automated then I can improve the parser to make them look better.**

I manually descriptions and its options, because there is no easy way to extract options details as they are not any method or class property. That said, we have full control and flexibility of formatting descriptions.

**Comment by mostaphaRoudsari** [comment]
Thanks for the clarifications. I can update the code to works as you like.

For descriptions with options I suggest to use * instead of - and leave a space between the two. That will be formatted correctly in md by itself. 

For instance:
```
Use this command to convert closed geometries to honeybee rooms.
Options:
-SkipExistingRoom: set to Yes to only convert non-honeybee-room geometries
```

Should be this:
```
Use this command to convert closed geometries to honeybee rooms.
Options:
* SkipExistingRoom: Set to Yes to only convert non-honeybee-room geometries
```

Which will then render like this:

## `HB_MassToRoom`

Use this command to convert closed geometries to honeybee rooms.

Options:
* SkipExistingRoom: Set to Yes to only convert non-honeybee-room geometries

We can also do fancy stuff like this one:

## `HB_MassToRoom`

Use this command to convert closed geometries to honeybee rooms.
  <details>
    <summary>Options</summary>
    <ul> SkipExistingRoom: Set to Yes to only convert non-honeybee-room geometries</ul>
  </details>

## `next command`

**Comment by MingboPeng** [comment]
Thanks, I will try to add this in CI. Do you think we can just add this document file to repo/docs or github page?

**Comment by mostaphaRoudsari** [comment]
We can generate the document and then push it to the GitHub page. We do this almost for every single ladybug tools repository.

See here:

https://github.com/ladybug-tools/ladybug/blob/3c709eb93b18021eecc17c74bcbce620f67e5dde/.travis.yml#L35-L47

or this one which is more similar to your case that doesn't use Sphinx:

https://github.com/ladybug-tools/queenbee/blob/c4693b1b628a931d85c466513e6d3de85401c7cb/.travis.yml#L31-L43

and here is the docs.py:

https://github.com/ladybug-tools/queenbee/blob/master/docs.py

Let me know when you have an updated version of the XML file and I can update the code. Unless you want to do it yourself.

**Comment by MingboPeng** [comment]
Thanks @mostaphaRoudsari, I have added to release process, but somehow it cannot add the md file back to repo. 
Any chance that you know what happened? And how do we add this md file to github page? do we have to convert it to html first?

https://github.com/ladybug-tools/honeybee-rhino-plugin/blob/ad94ceda6e7b3623f6d050e288d4051a970ce600/.github/workflows/release.yaml#L39-L47
![image](https://user-images.githubusercontent.com/9031066/78705018-d467d680-78da-11ea-8a87-8e3b3104fac2.png)

**Comment by mostaphaRoudsari** [comment]
Hmmm. I can take a look tomorrow. I haven't done it with GitHub workflows before. It should be similar to Travis. We shall see.

**Comment by mostaphaRoudsari** [comment]
@MingboPeng should we close this issue or do you still have issues with deployment?

**Comment by MingboPeng** [comment]
Thanks for your helps, I have fixed the descriptions as well.
