### ISSUE TITLE
Where to save keep default library of program type, construction, schedule

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/honeybee-rhino-plugin#42]
@mostaphaRoudsari @chriswmackey 
Have we decide where to keep default library locally.
Are we still using c:\Ladybug or under user folder?

**Comment by MingboPeng** [comment]
All honeybee standards saved at: C:\Users\USERNAME\honeybee

**Comment by mostaphaRoudsari** [comment]
Is there a subfolder for standards? `%USERFOLDER%\honeybee\standards` or `%USERFOLDER%\honeybee\libs\standards`?

**Comment by MingboPeng** [comment]
This is current folder from Honeybee grasshopper installation:
![image](https://user-images.githubusercontent.com/9031066/75783663-eaf49e00-5d2e-11ea-8877-9a51111f485b.png)
But I think one folder called `standards` makes more sense, instead of current two. It is really confusing even for me who work on these folder every day.

**Comment by mostaphaRoudsari** [comment]
Oh OK. At least we have subfolders 😀. For changing the folder structure I think we should open a separate issue and get some feedback from @chriswmackey on this one.
