### ISSUE TITLE
Semantic Release failed

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/honeybee-rhino-plugin#89]
https://github.com/ladybug-tools/honeybee-rhino-plugin/runs/498057480?check_suite_focus=true
![image](https://user-images.githubusercontent.com/9031066/76323478-248f5100-62bb-11ea-9cdf-9e61870662c0.png)

Hi @AntoineDao, it says `401 Unauthorized` after @mostaphaRoudsari  added the GH_TOKEN and I merged the PR.
I couldn't find any related post for semantic-release. Do you think this has something to do with how we set up the GH_TOKEN? 
![image](https://user-images.githubusercontent.com/9031066/76324100-ecd4d900-62bb-11ea-8135-5fdc1187afb1.png)

**Comment by mostaphaRoudsari** [comment]
It should have been my mistake. I updated the token and re-ran the workflow. It looks to be working as expected.

**Comment by MingboPeng** [comment]
@mostaphaRoudsari, it shows the same error again when I add a new PR.

**Comment by mostaphaRoudsari** [comment]
Not sure what is going on. If I run it from the interface it works fine:

https://github.com/ladybug-tools/honeybee-rhino-plugin/runs/499094962

Have you tried to re-run it from the interface?

**Comment by AntoineDao** [comment]
The plot thickens! It seems that the token is recognized but must be running a specific operation that it is not authorized to perform.

You can see the tags are still created but the release creation process fails for some reason:
![image](https://user-images.githubusercontent.com/20436635/76378547-61317a00-6399-11ea-8435-2f752034e93b.png)
This explains why it works the second time. Semantic release sees that a tag already exists for the commit so it doesn't re-run (or re-fail).

**Comment by MingboPeng** [comment]
It only creates new tags, but never released.
![image](https://user-images.githubusercontent.com/9031066/76378113-03fae180-6323-11ea-9fb5-b1f23e64d163.png)
This is the log the second time:
![image](https://user-images.githubusercontent.com/9031066/76378667-63a5bc80-6324-11ea-8f6a-cf3f22915b41.png)

**Comment by MingboPeng** [comment]
@AntoineDao Those zip files are source code, it doesn't zip those compiled files.

**Comment by AntoineDao** [comment]
Yep I noticed that too. I reckon that the token is bust but that github actions is still committing the changed tags...

**Comment by AntoineDao** [comment]
We need to work on those asset names. But the rest works: 
![image](https://user-images.githubusercontent.com/20436635/76379201-35af8f00-639b-11ea-9506-15dc28f1f937.png)

![image](https://user-images.githubusercontent.com/20436635/76379081-d81b4280-639a-11ea-8ad5-236584224158.png)
I'll fix this just now.

@mostaphaRoudsari the token you used must not have had the right permissions. I created a new personal access token for myself and used that as a GH_TOKEN secret. 

I gave this token full repo scope:
![image](https://user-images.githubusercontent.com/20436635/76379130-000aa600-639b-11ea-9f4b-d1a842692226.png)

**Comment by AntoineDao** [comment]
Right, after a bit of fumbling I think my job here is done!

https://github.com/ladybug-tools/honeybee-rhino-plugin/releases/tag/v0.20.0

@MingboPeng would you mind waiting for @mostaphaRoudsari to add a new token with the correct oauth scopes as indicated above before closing this issue?

**Comment by AntoineDao** [comment]
PS: I fixed the zipped package names here so it should look better on next release: https://github.com/ladybug-tools/honeybee-rhino-plugin/commit/b0e1a1dcdd816f1e0bd8751f66da3796689e5709

**Comment by MingboPeng** [comment]
@AntoineDao  Thanks so much!

**Comment by mostaphaRoudsari** [comment]
OK. I create a new secret. Let's see if that solves the problem.

**Comment by MingboPeng** [comment]
Thanks @mostaphaRoudsari  @AntoineDao , everything works fine now:>
