### ISSUE TITLE
HB_RunSimu  command only save model to json.not osm file.

### ISSUE THREAD

**Issue by ymg2007** [ladybug-tools/honeybee-rhino-plugin#97]
Hi,Mingbo. This plugin is amazing. I just installed the Visual Studio to study C# for Rhino and Grasshooper. I found this plugin on the morning. I decided to try it .I downloaded this plugin and used  Visual Studio to build it. And I installed rhp to Rhino,successed. After run some rhino command such as  HB_MassToRoom\HB_AddShade，I found a small bug for HB_RunSimu. This command only save the honeybee room in rhino to json, not to osm file. Maybe it is something wrong when I build this plugin.

Hope for your reply.
Here is the screenshot for my work.
![20200316171900](https://user-images.githubusercontent.com/24608776/76741370-67b15e80-67aa-11ea-906e-6868e8223b0d.jpg)

![20200316171924](https://user-images.githubusercontent.com/24608776/76741373-697b2200-67aa-11ea-8e0a-efa2dcdd65d8.jpg)

**Comment by MingboPeng** [comment]
Thanks @ymg2007 for testing out, we are still heavily developing this plugin, please do not use this for any real project yet, but it is ok for you to play around.

This plugin has a lot of dependencies (honeybee-energy[cli] and others) and resource libraries. You will need have all of them installed for this plugin to work correctly. 

I am currently working on an Installer, which will help you to do all installation works.

**Comment by ymg2007** [comment]
Yeah,I got it. Waiting for the stable version.
